# Dockerfile from https://github.com/nautobot/nautobot-lab/blob/main/Dockerfile
# Example from https://containerlab.dev/install/#__tabbed_3_2 
# FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04
FROM mcr.microsoft.com/devcontainers/base:1.0.9-ubuntu22.04 


# RUN bash -c "$(curl -sL https://get.containerlab.dev)" 

